package cn.witeye.iaac.mark.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
	}

	public java.lang.Long getExpireAt() {
		return getLong("expireAt");
	}

}
