package cn.witeye.iaac.mark.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	public void setModuleId(java.lang.Integer moduleId) {
		set("module_id", moduleId);
	}
	
	public java.lang.Integer getModuleId() {
		return getInt("module_id");
	}

}
